# Generated by Django 3.1.7 on 2022-03-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public_card_manager',
            field=models.BooleanField(default=False),
        ),
    ]
