# Generated by Django 4.0.2 on 2022-03-03 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=70)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='uploaded_imgs')),
                ('card_color', models.CharField(default='rgb(233, 236, 239)', max_length=30)),
                ('is_public', models.BooleanField(default=False)),
                ('linked_card', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('image1', models.ImageField(blank=True, upload_to='uploaded_imgs')),
                ('image2', models.ImageField(blank=True, upload_to='uploaded_imgs')),
                ('image3', models.ImageField(blank=True, upload_to='uploaded_imgs')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
