# Generated by Django 4.0.2 on 2022-02-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
