# Generated by Django 4.0.2 on 2022-02-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_card_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, upload_to='uploaded_imgs'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, upload_to='uploaded_imgs'),
        ),
    ]
