# Generated by Django 3.1.7 on 2022-02-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_image_post_image1_post_image2_post_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_color',
            field=models.CharField(choices=[('bl', 'bg-primary'), ('yl', 'bg-yellow-500'), ('rd', 'bg-red-500')], default='yl', max_length=30),
        ),
    ]
