# Generated by Django 3.1.7 on 2022-02-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20220226_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_color',
            field=models.CharField(choices=[('bg-primary', 'bl'), ('bg-yellow-501', 'yl'), ('bg-red-501', 'rd')], default='bg-yellow-500', max_length=30),
        ),
    ]
