# Generated by Django 3.1.7 on 2022-02-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20220227_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='linked_card',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
