# Generated by Django 4.0.2 on 2022-03-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_card_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_color',
            field=models.CharField(default='rgb(233, 236, 239)', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
